---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
  annotations:
    flux.weave.works/ignore: "false"
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0
spec:
  releaseName: home-assistant
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: home-assistant
    version: 0.9.6
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 0.99.3
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
      storageClass: "rook-cephfs"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    vscode:
      enabled: true
      image:
        repository: codercom/code-server
        tag: 2.1544-vsc1.38.1
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-type: "basic"
          nginx.ingress.kubernetes.io/auth-secret: "nginx-basic-auth-jeff"
          # nginx.ingress.kubernetes.io/auth-trust-headers: "true"
  valueFileSecrets:
  - name: "home-assistant-helm-values"
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hass-postgresql
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~11
spec:
  releaseName: hass-postgresql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: postgresql
    version: 6.3.9
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.5.0-debian-9-r34
    postgresqlUsername: "homeassistant"
    postgresqlDatabase: "homeassistant"
    replication:
      enabled: true
      slaveReplicas: 2
      synchronousCommit: "on"
      numSynchronousReplicas: 1
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      # storageClass: "rook-cephfs"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    volumePermissions:
      enabled: false
  valueFileSecrets:
  - name: "hass-postgresql-helm-values"
