---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: hass-postgresql
  namespace: default
  annotations:
    fluxcd.io/ignore: true
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~11
spec:
  releaseName: hass-postgresql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: postgresql
    version: 6.3.11
  values:
    image:
      repository: bitnami/postgresql
      tag: 11.5.0-debian-9-r34
    postgresqlUsername: "homeassistant"
    postgresqlDatabase: "homeassistant"
    replication:
      enabled: true
      slaveReplicas: 2
      synchronousCommit: "on"
      numSynchronousReplicas: 1
    persistence:
      enabled: true
      #accessMode: ReadWriteOnce
      storageClass: "rook-ceph-block"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    volumePermissions:
      enabled: true
  valueFileSecrets:
  - name: "hass-postgresql-helm-values"
