apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
spec:
  releaseName: vault
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: master
    path: .
  values:
    server:
      tolerations: |
        - key: "arm"
          operator: "Exists"
    ui:
      enabled: true
