apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
spec:
  releaseName: vault
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: master
    path: .
  values:
    server:
      tolerations: |
        - key: "arm"
          operator: "Exists"
      standalone:
        enabled: false
      ha:
        enabled: true
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path = "vault"
            address = "consul:8500"
          }
    ui:
      enabled: true
    #   serviceType: "ClusterIP"
    #   annotations:
    #     kubernetes.io/ingress.class: "traefik"
    #     ingress.kubernetes.io/auth-type: "basic"
    #     ingress.kubernetes.io/auth-secret: "traefik-basic-auth-jeff"
    #     ingress.kubernetes.io/auth-trust-headers: "true"
    #     traefik.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/16, fe80::/16"
