apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fluxcloud
  namespace: flux
spec:
  encryptedData:
    slack_url: AgAGtycG9Hhp+gGP0P1trCwz2FEqpKEEPfLZuErRkByCAQC+29qB1RySGQT5HNh94RAsUb5aG02RGJwMWcWL4o8WZDOx0v+8rvnJf6dpe4CMFDlW3ks5SKia0P8n/ogjOy1VOyaWVMi9ZAPX/ZdvomEyPq3cfFWdSP6YMaGnIRDWRb6Vi/pChkPn69jO+k+Gfr4oWRoq0LY6ZE9w++MOe8TYU3YcApcMQLODMHEIW0VGCztiFAhmXobDTxAOZIfm6u/ZGCCOnpcarDuBsy3SFhGqONT31vgh5XmbnIx71HGahUGAeXxDVJCR7QFxqYWaPmHnkxO8GxROTlZAizQGzzWZygm5HJql5/skMkcxZEL3LsQOF+W3dxXTF4a5TMvne92McmovkGUCh0vkyG7WGL8skIcy5M1bdGaoibXtZaytWj5mVbr47vLk+xptiD2gVNsn4bP5OS7VrVNJP5ZkMN2JIt24bnON4QQ8zM90eZNIu8PG18QC5H1SkhrdTjwyE4gWCSuDOLIoqqVcPz1FnNmTxBizWoWzMEgXmXlQMWMaQaDIG6L+w2Dsp5oCHiVJXxPf/JbB2HCc+OaXKenjMfWZxZdvQzDZTAXR5fBLYXHl5cuXHeu41FogRtDUAt1mJ812Ri4fPgiXJRyMS+6JDHlhqhw4SUPj+vhpXocu3ncVVkiZvyY1PdZE+RVSMDoX9GcxJEqSbBTsXfT+R3n+ONAiS70kbcbGWoZwyh/Vj/93awbylkrHXJTzH8Gu6+OXF9MWw/Po4CDzkx6beVBddv/gLCQns6XmuWK2M7Wd4g==

