---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'glob:amd64-2.*.*.*'
spec:
  releaseName: sonarr
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: sonarr
    version: 2.0.6
  values:
    image:
      repository: linuxserver/sonarr
      tag: 'amd64-2.0.0.5338-ls37'
      pullPolicy: Always
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rook-ceph-block"
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        accessMode: ReadWriteMany
      tv:
        enabled: true
        existingClaim: nfs-media-pvc
        subPath: Videos
        accessMode: ReadWriteMany
  valueFileSecrets:
  - name: "sonarr-helm-values"
