---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rtorrent-flood
  namespace: default
  annotations:
    fluxcd.io/ignore: "true"
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:0.9.*
spec:
  releaseName: rtorrent-flood
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: rtorrent-flood
    version: 3.1.2
  values:
    image:
      repository: jfurrow/flood-ui
      tag: latest
    uid: 1001
    gid: 1001
    guiService:
      type: ClusterIP
      port: 3000
    btService:
      type: LoadBalancer
      port: 49161
      loadBalancerIP: 10.2.0.159
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: rook-cephfs
      data:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
  valueFileSecrets:
  - name: "rtorrent-flood-helm-values"
