apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: kured
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: kured
    version: 1.3.1
  values:
    image:
      repository: billimek/kured
      tag: 1.2.0
    tolerations:
      - key: "arm"
        operator: "Exists"
  valueFileSecrets:
  - name: "kured-helm-values"
---
# apiVersion: fluxcd.io/v1beta1
# kind: HelmRelease
# metadata:
#   name: kured-arm
#   namespace: kube-system
#   annotations:
#     fluxcd.io/automated: "false"
# spec:
#   releaseName: kured-arm
#   chart:
#     repository: https://kubernetes-charts.storage.googleapis.com/
#     name: kured
#     version: 1.3.1
#   values:
#     image:
#       repository: quay.io/anguslees/kured-arm
#       tag: latest
#     tolerations:
#       - key: "arm"
#         operator: "Exists"
#     nodeSelector:
#       kubernetes.io/arch: arm
#   valueFileSecrets:
#   - name: "kured-helm-values"
