apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgCY/J8tZrmpTrf1rjjLE6rqDqv048/6E9VulpPNiMOpKLs02heALf2J/2po24x9yJwpUzgLdAS19KXYHJVPluRnlCDUMsAGWlTd4BgaeGzpPwDqUCA2eBbnn7FgXAzS02d5Qup1gB3HoJZ7nY5mbQs8r6VFGbIlN6z40fM4KD2vTsWSrmJirMKBpaIJbyBGqHyL+P/Pz4r2e2Z19GAYDBddfSgH3zMTolspL/zBIGK/QErt2P2cJ3ThwAV5PaMzUpN7ltO+4s4VofVEzfeTEnAiW9AM/P/pt+uBFWDyfJgNXGSz/vp2lScPE5QtzGnWrg/alDQAvPqZPztca0b0znGVhfk5SzJ+0k+FYEjXBye6dyGGjjPM0z7cdHMJGrcps2BgndJGlUtnHsmgLJk9md4rEu62QrkAyRBA8OQgo2/ehz060FiU4wap8MU85O5KCsd8RvUbrzB/UxhIZ1lzXAzEG13nqFplnyGnSi3fEVeec4VM34vTLvBipzf6vjsIm7n+4SjKC9glGFNSFWzjqL19cl1Cl/ZvwmKCJLwkn59nRUXn6Rim0awziQjcKYoG0JiRQ2CjNX9FrHEvlPtEWC+ouIO6JYWhqjQlF+IH2rVuSi0M7fZNxEpLGONzV+2lbbVM0Hi+hgfKCRPlw53CxjoTeKusfAxsxP58YqHBbgLzROoc8tXS8btbMd1/kCSiD5CUJYtxsWoso3CK4oFo/H1FK0uaOxFRMB1sOJET8LmEG/6UMN2a446IUHX7KqAWp2Tz446lptELm4nRpd1IsorQ1JrMePB8nI4828mVVosA7/Vxlhyr1v7VkOAQdkJIpGYEc07Wb7EqcT04EBk=

