apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kured-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgA31uIz/0OUg1thbvrijFPtiiSx157Z925KjS6d8A1wMl7pdPtNuoYhTGzZShcJdhOvw7GPa9zDi3ouZC4DbMBYbXZsjOcdOGzAWqrYR81Oypn+gRBx14nbLRMcuBV5cRgZ400FVYCxDpNZHgBmws9lOTpwTNbexnc8Cml4vKmQYpgBkHdZtu1f1dmZnZYuC36BJF5SZuDWo8iypLyU7UGZ4VxdYuPw5ux7wcmVqmwX/YGSolUYRns6yfUZXrUGkv4rljrMyR47sLp7mHrvHMoLgWGCdPs8e+AJUjaVKtP1oHuw9HVm/W3ipXXN4klkGmHO1JhRnHc/lyrEgBCuYUZn0al9zaLHNKmKyNf3Pe9ZD/erwr/9yTTthH0V8ZaLooE4xBSVLf+G4EYXgs2laGfX4WtO1uv7tjxQikIp8TV5OIYZOMAYrnRJi4HTunGHw9TO8Vnk64Ai6TJ74loQytBrtZW0WprB9/iD6m6Ig0LnzNH61T8+yZVIjg3CANUgMlqLI/hXVVRjJvCVW0zIYoWVKryb4znIiPDRFybrBCnlqVfPbOZ1D3nieRYxApEFQ2PYbH7OvWw5NKzGT5t2hcdOiTjg1SoVut0JKTrgiRxE6foUqrn9vYf4f9W1PQG0+D5ZglLU8lYhH5ZVatq+rZghK5Irf8z6lStuW97UtwCqJ8whWcbc8fRFfyC15geqD3Er50WFpaGo/Xd+mYB9wo0CWWMpZP2btJkVsGnRDEsy1L3lJK4ocaocYW0/rb4jWo+Ygu99e0am3G/MyudrN0U9mq9tRZXDykV9e5S9AuD36JRxAIcbij3u5aSLsWpA+XEJDePrt0iUP/kpbw8=

