apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: kured-helm-values
  namespace: kube-system
spec:
  keys:
    - slack_url
  path: secrets/kube-system/kured/kured-helm-values
  type: Opaque
