---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~v0.
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io/
    name: cert-manager
    version: v0.10.0
  values:
    webhook:
      enabled: false
    extraArgs:
    - --dns01-recursive-nameservers=1.1.1.1:53
    - --dns01-recursive-nameservers-only
