apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: vault
spec:
  releaseName: consul
  chart:
    git: https://github.com/hashicorp/consul-helm
    ref: master
    path: .
  values:
    server:
      enabled: true
      tolerations: |
        - key: "arm"
          operator: "Exists"
    client:
      tolerations: |
        - key: "arm"
          operator: "Exists"
