apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgAWk4n9PMHm9UmnCEGMyg21/UYptZZJAhPruFSuXXXf1wd7y4R4jSonZZ6njApNFxrum0CLvzSLXE4XeizlOQV3zKqFQwwHYfzKk5euWgrzPObtrSXGBQx3NQvooneoUz0LWn1hdMXLyx4otTq6lGynv93H++kW+Y8TvAO0Nffi/804rWoTjRAL81tvu8X5s5F+gNT/i7l3iUiTafL6fq/wqWkB1YTrEReoLO6KhQkuZADvzOK6dWwxiNcgnG8fLq4MRMbITPjNnlNaiWU6j5sonnMBWESNvX3aUBCgHtDbb9zr/bJFrP6mPYktHXe+YO3v1+Zv5L7Ms6OKI0zsT53rmOnmlF1AE+AD9X1ONElLxmDhQuyD3bZyDGmyMNVvSjjE15/97wtcZJZrS1JgLukn9LKBpi2iKKMGVINqfifrMKwuGc/2Jr/PIzcphMfBbhbvvcpKCNt8xeIpy0UYDaK4lfir+t53r0NDNd2DFIFfFpR/nMF9DkAyJo7X8R6DaAGtJdXYrjuIsRuzQEKSZcj/FDRNOC/TkOLuqjRk8hM+YjGfmqp+ns10kuoy1XGFQiLws3Moxtus9DA4aUb/AYO8KlDgfGCBosop//KVpB/ewHA9Bd0/izTAlDQwos8I4WxKY5k9Gih1jOts1sKskHSxfuG3kYkqt2T3rqBt+rqatF5NrjkR+h3/zMXM88bHYELWNcMEN9VNESMh1AEQ6k2wzpkIwfGDt322i/V9Y1mpQ4X5HI4uTAWe8YpbsYipuQky4rNxgnSk2FRJ4wo14LRNFyrtanGTNdMPRvYlOzp6sssDuHDMfWfaLwzzsfxFx/3xrXtsWxhXbGl2+jffE9NhIp4LiRz5ZkopFGdL6sgeAm4BGCO8koKHBx9wmHFyzTUDws+EmicY5SdqNDvA9PiQUvePrL9ueLklMJHEY3PfyX4P2g7u/kE8lvMNrSKlnJ9mTl0EAGRc4f4zGulgIB5LPBpT1a1D4A==

