apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-helm-values
  namespace: kube-system
spec:
  encryptedData:
    values.yaml: AgCyPFjgiXmW74YNLGEGMLEAV0dCwtb7zfy03sN5n8W6Uvu8WuweN3RWtmwI4sgx3QR+g4kNgBQXLaXhyZ/4K/ERmiZ5SV76MWhFTBkopXuzYTkXmODtYBWph/MO3IwZ7fXfwnfN6icS+EXXSS7XafF/RxQwyPI6k3uWJ1swtcF55LxD2bX9xm0cYhA8TRJsftCEymus7SnnzjKlctakWCRGOttfqU6VAq9ay0lvMdqHdncCZ7892EUiRzklfKdhb6Yh3ZaEOfyoI89K3FcO17VDfutmDPxxLeJarQuHVjN3JLjh7LItK1PSg6CRGSITmA5ieyTUCb43zGteEZoxEpQyM8HtByIKV9q08inQhrsoDieYteuDxvrRQ5ZYis0qPEfmlapAqRpAOEeVgnEbFepaM8RQfe3D2ZAphpT/G6ibhnr4Th4FCJBUcWKuJeq3z/mvKZpuet5Vxl+nFOdQW4xNVEBvD+j75eb+wfr6vDav9CzpWArro27C54qnxBxlctrxEJTTrnJaCZBGaOOahe6e6jiSH4B9x8vN1K/HoLlHHP9M5JxuB8L+Tqv+3qqI9qlRIoA8UUUGwpmkkR3P50CcI+4nXP4vyvP5a/wOObGTMrfCvkLZFsgL/uUpNaimpzR4kFBDG8GrUivVusOdrySNOtyWxqCKN4Kyd8wsPNyqSqSfKOoxj7OjJ/nJ7mSEp/2mjqc0D15z98LX2ldH4qXtXCMLfExOrv5u4H9hTVsnTfZ3yvTKvTw+XCEI5MP20H2u7ta90lOfZbfGrH9FFfWaBteDhc/Is8ECEBOKShk8D4FHZJ7IRmUNuRA4SBwbs9lYX8DT5VXkXOrDTABcqpfExRZuh5YQCtcbIgpfgoQ+jcjDWXE/Xj7WoVSNTXOFYIVGdTBbkVzJA55781is4oFZjN4ev1iawbZNMIQeXbZCb6iBHfLHYYiKL0gWoVSlSjqTlIUA940OZK0KxUlXVjtagvFuHtfBdg==

