apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: traefik-basic-auth-jeff
  namespace: kube-system
spec:
  encryptedData:
    auth: AgA8LnuyoRmTTG5cSm5NvPf1NBSLgv9XQ9oip3qyFPZqF4OYeCjDP2KcUk46nSQyHPUAyoaOqkYH+Gmlxq0v39I3GbtuogKIO+CJLXZBeMz0578QsHsTszrknXdF+tVz6UZqtpmm0nu/j0QD3HxJtMSCkLfhK7fh7fVYRVyWmWf41hBAN4gQNy7fM2Zz0WUykYrhfRamlK6/pBup8wYrsT6J7MNJ5LkWhJIFUz4tWC1KPrKc8jF8i9YBTsT2gTJifQGPI2chhnK+E1qK5o1eEiaej2done8f0hyIj57XK6lfsd57XhK5SY17ZThlCjDACoGPYFRXiAm0ivqBLPp4Wf0C3m1PyJde619S2FxZcl4LxNBIIyq0rok9qG4dw3X948LgYrl5A7jLQS7UUg1BziLPIkfaSB/+mU82ftgFFD5LI9wVn4p/4hjrtTDhBUpp6P564dkXV8xwx1RviGlQfbixnTZmdNOdGzF+1Gq5C+JIWN1AuBjGtzL3QPHzneXAkV3qWpCykp1S3XAb5xnAaQnTFY0mE+f9bDyaT1gUh2nF3NxDqsMQHj+S8R+bhkB2IJC3ntda9dbRov3NqGPcr78t6XBza5sXn1fr19DP3i3mi6aDgu44T+xmZlTl80tfsarNFvAwrKMWhKTWJjQPaw5LXRZqqIaLx5Qw0OOlLFiUcMfdhYXKAnGbbi9qfVylkwGULO63sJfRg9dR8SgAaA9Qn9EsEZjG50RHIbCnSjmFlvMlYCDs18p8pR8=

