---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: rook-ceph
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: v1.1.2
  values:
    csi:
      kubeletDirPath: /var/lib/rancher/k3s/agent/kubelet
