---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hubot
  namespace: default
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~3
spec:
  releaseName: hubot
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: hubot
    version: 0.0.2
  values:
    image:
      repository: billimek/hubot
      tag: latest
    hubot:
      config:
        HUBOT_GRAFANA_S3_STYLE: 'path'
        HUBOT_GRAFANA_S3_BUCKET: 'public'
        HUBOT_GRAFANA_S3_REGION: 'us-east-1'
        HUBOT_HOME_ASSISTANT_EVENTS_DESTINATION: '#general'
  valueFileSecrets:
  - name: "hubot-helm-values"
