---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v1
spec:
  releaseName: velero
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: velero
    version: 2.1.6
  values:
    image:
      repository: gcr.io/heptio-images/velero
      tag: v1.1.0
    metrics:
      enabled: true
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/rancher/k3s/agent/kubelet/pods
      privileged: false
    # schedules:
    #   daily-backup:
    #     schedule: "0 6 * * *"
    #     template:
    #       ttl: "168h"
  valueFileSecrets:
  - name: "velero-helm-values"
