apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-helm-values
  namespace: monitoring
spec:
  encryptedData:
    values.yaml: AgAuOk8tX4qGiknJtF6GCPebsAqle0hC8HX8uyxEFoTaUMnHHev6W8eCa7mfkjLazynHadd+dbOFCclwQQk1EOjvhB7K8xiL0qkIk150dMkBl6Ykdv8xeX7/Zl2jvdjuidxVeIvnht6fHzigoWU5Blgu6TpyoILQPlibiVSH1QQD8nEAgAVfYJ7/80JiJ6pFf+gJSD7OBGHcNyv06SYztM99oojrkYPk73Nf3Wm1rv89bQ05EI97/dcb1ja0+hStP9wNXgu8hTaGwCXM24Hwux1ckfVmcCyfMYMiyPpVxnrSanhO9zp+MJQjWu+kvFBYtuATcz5t5sVo6mCoKHLfYbq/WyI/YqZ9/Pi7kGYf/bZ1DbS/CabFpIGaLQJCjmKJNDRVSfjNFk1rAuMcimNcinmPXJqUETiSgf8EBSLUHdY9Vo0BnwDGfNQp4erfVIKFFXWxTKFfm/6Yvl/vG44TlCErD5EduRmLI37PYRNwsoruay6oNFN9U+xlKsB+BUl/FS1uZyLKsSwj/mAb1pjCADwlI96hHnQ1cr9gLGA8y0xE+gxS9N47bl4kvvjox/9L3hPHeAAl/OevaurmerHZEdRP0UgoZ3YbUCBJzDGcXheeGNTIdm/v8WJt0LBc5QD/SU2M/zMQJnpAKn2t3zyDSKi1qFdSrnYwDgZDNSD8BrOkSuiUuHuvf7pbKHJ17p81pfuvhuKvfqwyfbhlj+dw5aTQ3aRDUQ==

