---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+)$'
spec:
  releaseName: influxdb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: influxdb
    version: 1.3.3
  values:
    image:
      repository: "influxdb"
      tag: "1.7.8"
    service:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.220
    persistence:
      enabled: true
      size: 50Gi
      storageClass: nfs-client
    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 4Gi
        cpu: 4
    config:
      opentsdb:
        enabled: true
    tolerations:
    - key: "arm"
      operator: "Exists"
