---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: comcast
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: true
spec:
  releaseName: comcast
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: comcast
    version: 1.0.6
  values:
    image:
      repository: billimek/comcastusage-for-influxdb
      tag: latest
    debug: true
    config:
        delay: 3600
        influxdb:
            host: influxdb
            port: 8086
            database: comcast
  valueFileSecrets:
  - name: "comcast-helm-values"
