---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: comcast
  namespace: monitoring
spec:
  releaseName: comcast
  chart:
    repository: https://billimek.com/billimek-charts/
    name: comcast
    version: 1.0.6
  values:
    image:
      repository: billimek/comcastusage-for-influxdb
      tag: latest
    debug: true
    config:
        delay: 3600
        influxdb:
            host: influxdb
            port: 8086
            database: comcast
  valueFileSecrets:
  - name: "comcast-helm-values"
