apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: glob:v0.*
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.4.0
  values:
    image:
      repository: quay.io/bitnami/sealed-secrets-controller
      tag: v0.8.1
    tolerations:
    - key: "arm"
      operator: "Exists"
