---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chronograf
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: true
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.7
spec:
  releaseName: chronograf
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: chronograf
    version: 1.1.0
  values:
    image:
      repository: "chronograf"
      tag: "1.7.14"
    persistence:
      enabled: true
      storageClass: nfs-client
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-type: "basic"
        nginx.ingress.kubernetes.io/auth-secret: "nginx-basic-auth-jeff"
        # ingress.kubernetes.io/auth-trust-headers: "true"
    tolerations:
    - key: "arm"
      operator: "Exists"
  valueFileSecrets:
  - name: "chronograf-helm-values"
