---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: vault-secrets-operator
  chart:
    repository: https://ricoberger.github.io/helm-charts
    name: vault-secrets-operator
    version: 1.1.1
  values:
    image: ricoberger/vault-secrets-operator
    imageTag: 1.1.1
    vault:
      address: "vault"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
    tolerations:
    - key: "arm"
      operator: "Exists"
  valueFileSecrets:
  - name: "vault-secrets-operator-helm-values"
