---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: vault-secrets-operator
  rollback:
    enable: true
  chart:
    repository: https://ricoberger.github.io/helm-charts
    name: vault-secrets-operator
    version: 1.2.2
  values:
    image:
      repository: ricoberger/vault-secrets-operator
      tag: 1.2.3
    vault:
      address: "http://vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
