apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv-10g
spec:
  storageClassName: data
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.7
    path: "/tank/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc-10g
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data
  resources:
    requests:
      storage: 1Mi