apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-nextcloud-pv-10g
spec:
  storageClassName: data-nextcloud
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.10.7
    path: "/tank/data/nextcloud"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-nextcloud-pvc-10g
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: data-nextcloud
  resources:
    requests:
      storage: 1Mi