---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: unifi
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(5\.[0-9][0-9]\.[0-9]+)$'
spec:
  releaseName: unifi
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: unifi
    version: 0.4.2
  values:
    image:
      repository: jacobalberty/unifi
      tag: 5.11.47
    persistence:
      enabled: true
      size: 20Gi
      storageClass: rook-cephfs
    timezone: "America/New_York"
    runAsRoot: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    controllerService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.156
    stunService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.157
    discoveryService:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.158
    podAnnotations:
      backup.velero.io/backup-volumes: unifi-data
  valueFileSecrets:
  - name: "unifi-helm-values"
