---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(3\.[0-9]+\.[0-9]+-alpine)$'
spec:
  releaseName: rabbitmq
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: rabbitmq-ha
    version: 1.32.0
  values:
    image:
      repository: rabbitmq
      tag: 3.7.17-alpine
    rabbitmqMQTTPlugin:
      enabled: true
    rabbitmqWebMQTTPlugin:
      enabled: true
    service:
      clusterIP: ""
      loadBalancerIP: "10.2.0.202"
      type: LoadBalancer
    persistentVolume:
      enabled: true
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
    rabbitmqErlangCookie: "9uVNsf2plnpyslPjqUVaDmGTUml2wJlb"
    forceBoot:
      enabled: false
    tolerations:
    - key: "arm"
      operator: "Exists"
    resources:
      limits:
        cpu: 100m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
    initContainer:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
    definitions:
      permissions: |-
        {
          "user": "mqtt",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      queues: |
    #    {
    #       "name":"myName",
    #       "vhost":"/rabbit",
    #       "durable":true,
    #       "auto_delete":false,
    #       "arguments":{}
    #    }
    ## Sets the policies in definitions.json. This can be used to control the high
    ## availability of queues by mirroring them to multiple nodes.
    ## Ref: https://www.rabbitmq.com/ha.html
      policies: |-
        {
          "name": "ha-all",
          "pattern": ".*",
          "vhost": "/",
          "definition": {
            "ha-mode": "all",
            "ha-sync-mode": "automatic",
            "ha-sync-batch-size": 1
          }
        }
  valueFileSecrets:
  - name: "rabbitmq-helm-values"