---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: speedtest
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: true
spec:
  releaseName: speedtest
  chart:
    repository: https://billimek.com/billimek-charts/
    name: speedtest
    version: 1.1.7
  values:
    image:
      repository: atribe/speedtest-for-influxdb-and-grafana
      tag: latest
      pullPolicy: Always
    debug: true
    config:
        delay: 7200
        influxdb:
            host: influxdb
            port: 8086
            database: speedtests
