apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: descheduler
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0.2
spec:
  releaseName: descheduler
  chart:
    repository: https://raw.githubusercontent.com/komljen/helm-charts/master/charts/
    name: descheduler
    version: 0.2.1
  values:
    image:
      repository: komljen/descheduler
      tag: v0.8.0
    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: true
        LowNodeUtilization:
          enabled: true
          params:
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 40
                memory: 40
                pods: 100
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
            - requiredDuringSchedulingIgnoredDuringExecution
