---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'glob:amd64-v0.*.*.*'
spec:
  releaseName: radarr
  rollback:
    enable: true
  chart:
    repository: https://billimek.com/billimek-charts/
    name: radarr
    version: 2.0.7
  values:
    image:
      repository: linuxserver/radarr
      tag: 'amd64-v0.2.0.1358-ls36'
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    persistence:
      config:
        enabled: true
        storageClass: "rook-cephfs"
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        accessMode: ReadWriteMany
      movies:
        enabled: true
        existingClaim: nfs-media-pvc
        subPath: Videos
        accessMode: ReadWriteMany
  valueFileSecrets:
  - name: "radarr-helm-values"
