helmOperator:
  create: true
  createCRD: true
git:
  url: "git@github.com:billimek/k3s-gitops"
registry:
  rps: 1
  burst: 1
memcached:
  tolerations:
  - key: "arm"
    operator: "Exists"
additionalArgs:
- --connect=ws://fluxcloud
prometheus:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false
