apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
  labels:
    app: intel-gpu-plugin
spec:
  selector:
    matchLabels:
      app: intel-gpu-plugin
  template:
    metadata:
      labels:
        app: intel-gpu-plugin
    spec:
      nodeSelector:
        app: intel-gpu-plugin
      containers:
      - name: intel-gpu-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: billimek/intel-gpu-plugin:devel
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/intel_gpu_device_plugin"]
        args: ["-shared-dev-num", "4"]
        volumeMounts:
        - name: devfs
          mountPath: /dev
        - name: sysfs
          mountPath: /sys
        - name: kubeletsockets
          mountPath: /var/lib/rancher/k3s/agent/kubelet/device-plugins
      volumes:
      - name: devfs
        hostPath:
          path: /dev
      - name: sysfs
        hostPath:
          path: /sys
      - name: kubeletsockets
        hostPath:
          path: /var/lib/rancher/k3s/agent/kubelet/device-plugins
