---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red
  namespace: default
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+-12-minimal)$'
spec:
  releaseName: node-red
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: node-red
    version: 1.3.5
  values:
    image:
      repository: nodered/node-red
      tag: 1.0.1-12-minimal
    persistence:
      enabled: true
      storageClass: "nfs-client"
    tolerations:
    - key: "arm"
      operator: "Exists"
    flows: "flows.json"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/auth-type: "basic"
        nginx.ingress.kubernetes.io/auth-secret: "nginx-basic-auth-jeff"
    podAnnotations:
      backup.velero.io/backup-volumes: data
    timezone: "America/New_York"
  valueFileSecrets:
  - name: "node-red-helm-values"
