---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(0\.[0-9]+\.[0-9]+-v10)$'
spec:
  releaseName: node-red
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: node-red
    version: 1.3.1
  values:
    image:
      repository: nodered/node-red-docker
      tag: 0.20.8-v10
    persistence:
      enabled: true
      # storageClass: "rbd"
    # tolerations:
    # - key: "arm"
    #   operator: "Exists"
    flows: "flows.json"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "traefik"
        ingress.kubernetes.io/auth-type: "basic"
        ingress.kubernetes.io/auth-secret: "traefik-basic-auth-jeff"
    timezone: "America/New_York"
  valueFileSecrets:
  - name: "node-red-helm-values"
