---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: false
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0.
spec:
  releaseName: nginx-ingress
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.21.0
  values:
    controller:
      image:
        repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
        tag: "0.25.1"
      replicaCount: 2
      service:
        loadBalancerIP: 10.2.0.210
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          # namespace: monitoring
        prometheusRule:
          enabled: false
      # tolerations:
      # - key: "arm"
      #   operator: "Exists"
      extraArgs:
        default-ssl-certificate: "kube-system/acme-crt-secret"