---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: default
  annotations:
    fluxcd.io/ignore: true
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: 'regexp:^(1\.[0-9]+\.[0-9]+\.[0-9]+-.*)$'
spec:
  releaseName: plex
  chart:
    git: https://github.com/munnerz/kube-plex
    ref: master
    path: charts/kube-plex
  values:
    image:
      repository: plexinc/pms-docker
      tag: 1.17.0.1841-d42cfa161
    nameOverride: plex
    podAnnotations:
      backup.velero.io/backup-volumes: config
    kubePlex:
      enabled: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
    timezone: "America/New_York"
    service:
      type: LoadBalancer
      loadBalancerIP: 10.2.0.244
    persistence:
      transcode:
        enabled: true
        claimName: nfs-data-pvc
        subPath: plex
      data:
        enabled: true
        claimName: nfs-media-pvc
      config:
        storageClass: "rook-cephfs"
        # accessMode: ReadWriteOnce
    # resources:
    #   limits:
    #     gpu.intel.com/i915: 1
    #   # requests:
    #   #  gpu.intel.com/i915: 1
  valueFileSecrets:
  - name: "plex-helm-values"
